eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.23.239.76:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: api-gateway


  data:
    mongodb:
      repositories:
        enabled: true

      host: localhost

logging:
  level:
    com.stackroute: DEBUG

driverClassName: com.mongodb.jdbc.MongoDriver