server:
  port: 9098
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: user-service


  datasource:
    url: jdbc:mysql://localhost:3306/userdb

    username: root
    password: Root@123


  jpa:
    hibernate:
      ddl-auto: create-drop

driverClassName: com.mysql.jdbc.Driver


logging:
  level:
    com.stackroute.route: DEBUG