FROM openjdk:11

ADD target/spring-eureka-client-school-service-0.0.1-SNAPSHOT.jar  /src/app/music/spring-eureka-client-school-service-0.0.1-SNAPSHOT.jar

WORKDIR /src/app/music

ENTRYPOINT ["java","-jar", "spring-eureka-client-school-service-0.0.1-SNAPSHOT.jar"]